#!/bin/bash
# Asset Reorganization Script for The Tulip Weddings
# Copies and renames all images into public/images/ with clean SEO-friendly names

ROOT="/Users/zahiruliman/Downloads/Projects/thetulipweddings.com/public"
SRC="$ROOT/assets"
DEST="$ROOT/images"

echo "Creating new folder structure..."
mkdir -p "$DEST/hero"
mkdir -p "$DEST/bridal"
mkdir -p "$DEST/contact"
mkdir -p "$DEST/logo"
mkdir -p "$DEST/social"
mkdir -p "$DEST/hall/laman-puteri"
mkdir -p "$DEST/hall/kluang-glasshouse"
mkdir -p "$DEST/hall/barokah-village"
mkdir -p "$DEST/hall/villa-kemboja"

echo "--- Root-level public/ files ---"
cp "$ROOT/assets/images/hero/packages-header.jpg"       "$DEST/hero/packages-header.jpg"

echo "--- Root-level assets/ files ---"
cp "$SRC/AIMN9527.jpg"             "$DEST/hero/hero-wedding-01.jpg"
cp "$SRC/FHP_0022.jpg"             "$DEST/hero/hero-wedding-02.jpg"
cp "$SRC/FHP_0111.jpg"             "$DEST/hero/hero-wedding-03.jpg"
cp "$SRC/FHP_0255.jpg"             "$DEST/hero/hero-wedding-04.jpg"
cp "$SRC/FHP_0297.jpg"             "$DEST/hero/hero-contact-bg.jpg"
cp "$SRC/IMG_2257.jpg"             "$DEST/bridal/bridal-boutique-01.jpg"
cp "$SRC/IMG_2343.jpg"             "$DEST/bridal/bridal-boutique-02.jpg"
cp "$SRC/IMG_9575.jpg"             "$DEST/hero/hero-wedding-05.jpg"
cp "$SRC/IMG_9603.jpg"             "$DEST/hero/hero-wedding-06.jpg"
cp "$SRC/IMG_9607.jpg"             "$DEST/hero/hero-wedding-07.jpg"
cp "$SRC/K7300415.jpg"             "$DEST/bridal/decoration-pelamin-01.jpg"
cp "$SRC/K7309359.jpg"             "$DEST/bridal/decoration-pelamin-02.jpg"
cp "$SRC/KHR-24.jpg"               "$DEST/hero/hero-hall-bg.jpg"
cp "$SRC/KHR-266.jpg"              "$DEST/hero/kanopi-setup-01.jpg"
cp "$SRC/KHR-272.jpg"              "$DEST/hero/kanopi-setup-02.jpg"
cp "$SRC/KHR-30.jpg"               "$DEST/hero/kanopi-setup-03.jpg"
cp "$SRC/KHR-421.jpg"              "$DEST/hero/kanopi-setup-04.jpg"
cp "$SRC/MSY_3223.jpg"             "$DEST/hero/hero-wedding-08.jpg"
cp "$SRC/MSY_9176.jpg"             "$DEST/hero/hero-wedding-09.jpg"
cp "$SRC/MSY_9182.jpg"             "$DEST/hero/hero-wedding-10.jpg"
cp "$SRC/MSY_9586.jpg"             "$DEST/hero/hero-wedding-11.jpg"
cp "$SRC/dtulips 2.jpg"            "$DEST/contact/boutique-exterior-02.jpg"
cp "$SRC/dtulips.jpg"              "$DEST/contact/boutique-exterior-01.jpg"
cp "$SRC/k-1.jpeg"                 "$DEST/bridal/bridal-showcase-01.jpg"
cp "$SRC/k-2.jpeg"                 "$DEST/bridal/bridal-showcase-02.jpg"
cp "$SRC/k-3.jpeg"                 "$DEST/bridal/bridal-showcase-03.jpg"
cp "$SRC/k-frontstore.jpeg"        "$DEST/contact/boutique-frontstore.jpg"
cp "$SRC/k-indoor.jpeg"            "$DEST/contact/boutique-indoor.jpg"
cp "$SRC/k-onsite1.jpeg"           "$DEST/bridal/bridal-onsite-01.jpg"
cp "$SRC/kenalikami.jpeg"          "$DEST/hero/about-team-bg.jpg"
cp "$SRC/LOGO THE TULIP AI (1).svg" "$DEST/logo/logo-tulip-full.svg"
cp "$SRC/LOGO THE TULIP AI (2).svg" "$DEST/logo/logo-tulip-icon.svg"

echo "--- Hall: Laman Puteri ---"
cp "$SRC/hall/lamanputeri/hall laman puteri1.jpeg"  "$DEST/hall/laman-puteri/laman-puteri-01.jpg"
cp "$SRC/hall/lamanputeri/hall laman puteri2.jpeg"  "$DEST/hall/laman-puteri/laman-puteri-02.jpg"
cp "$SRC/hall/lamanputeri/hall laman puteri3.jpeg"  "$DEST/hall/laman-puteri/laman-puteri-03.jpg"
cp "$SRC/hall/lamanputeri/hall laman puteri4.jpeg"  "$DEST/hall/laman-puteri/laman-puteri-04.jpg"
cp "$SRC/hall/lamanputeri/hall laman puteri5.jpeg"  "$DEST/hall/laman-puteri/laman-puteri-05.jpg"
cp "$SRC/hall/lamanputeri/hall laman puteri6.jpeg"  "$DEST/hall/laman-puteri/laman-puteri-06.jpg"
cp "$SRC/hall/lamanputeri/hall laman puteri7.jpeg"  "$DEST/hall/laman-puteri/laman-puteri-07.jpg"

echo "--- Hall: Kluang Container Glasshouse ---"
cp "$SRC/hall/kluang container/kluang container hotel1.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-01.jpg"
cp "$SRC/hall/kluang container/kluang container hotel2.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-02.jpg"
cp "$SRC/hall/kluang container/kluang container hotel3.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-03.jpg"
cp "$SRC/hall/kluang container/kluang container hotel4.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-04.jpg"
cp "$SRC/hall/kluang container/kluang container hotel5.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-05.jpg"
cp "$SRC/hall/kluang container/kluang container hotel6.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-06.jpg"
cp "$SRC/hall/kluang container/kluang container hotel7.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-07.jpg"
cp "$SRC/hall/kluang container/kluang container hotel8.jpeg"  "$DEST/hall/kluang-glasshouse/kluang-glasshouse-08.jpg"

echo "--- Hall: Barokah Sri Village ---"
cp "$SRC/hall/barokah/barokah sril village1.jpeg"   "$DEST/hall/barokah-village/barokah-village-01.jpg"
cp "$SRC/hall/barokah/barokah sril village2.jpeg"   "$DEST/hall/barokah-village/barokah-village-02.jpg"
cp "$SRC/hall/barokah/barokah sril village3.jpeg"   "$DEST/hall/barokah-village/barokah-village-03.jpg"
cp "$SRC/hall/barokah/barokah sril village4.jpeg"   "$DEST/hall/barokah-village/barokah-village-04.jpg"
cp "$SRC/hall/barokah/barokah sril village5.jpeg"   "$DEST/hall/barokah-village/barokah-village-05.jpg"
cp "$SRC/hall/barokah/barokah sril village6.jpeg"   "$DEST/hall/barokah-village/barokah-village-06.jpg"
cp "$SRC/hall/barokah/barokah sril village7.jpeg"   "$DEST/hall/barokah-village/barokah-village-07.jpg"
cp "$SRC/hall/barokah/barokah sril village8.jpeg"   "$DEST/hall/barokah-village/barokah-village-08.jpg"
cp "$SRC/hall/barokah/barokah sril village9.jpeg"   "$DEST/hall/barokah-village/barokah-village-09.jpg"
cp "$SRC/hall/barokah/barokah sril village10.jpeg"  "$DEST/hall/barokah-village/barokah-village-10.jpg"
cp "$SRC/hall/barokah/barokah sril village11.jpeg"  "$DEST/hall/barokah-village/barokah-village-11.jpg"
cp "$SRC/hall/barokah/barokah sril village12.jpeg"  "$DEST/hall/barokah-village/barokah-village-12.jpg"

echo "--- Hall: Villa Kemboja ---"
for i in $(seq 1 20); do
  cp "$SRC/hall/villa kemboja/villa kemboja${i}.jpeg" "$DEST/hall/villa-kemboja/villa-kemboja-$(printf '%02d' $i).jpg"
done

echo "--- Social Thumbnails ---"
SOCIAL_SRC="$ROOT/social-thumbnails"
i=1
for f in $(ls "$SOCIAL_SRC"/*.jpg | sort); do
  cp "$f" "$DEST/social/social-$(printf '%02d' $i).jpg"
  echo "  Copied $(basename $f) -> social-$(printf '%02d' $i).jpg"
  i=$((i+1))
done

echo ""
echo "✅ Done! All files copied to $DEST"
echo "Verify with: ls -la $DEST"
